# default application setting
# encoding properties
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true

# spring properties
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bori
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bori_board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token-key: "asdlkfjalds3kjfdsl2kmcsd--ewifwei1"
